- name: Install Podman
  ansible.builtin.package:
    name: podman
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5

- name: "Creating /home/nleiva/etc-pihole"
  ansible.builtin.file:
    path: /home/nleiva/etc-pihole
    owner: root
    group: root
    state: directory
    recurse: true

- name: "Creating /home/nleiva/etc-dnsmasq.d"
  ansible.builtin.file:
    path: /home/nleiva/etc-dnsmasq.d
    owner: root
    group: root
    state: directory
    recurse: true

- name: Add HTTP to Firewalld to system-default(public)
  ansible.builtin.firewalld:
    service: http
    permanent: true
    state: enabled

- name: Add DNS to Firewalld to system-default(public)
  ansible.builtin.firewalld:
    service: dns
    permanent: true
    state: enabled

# The DHCP server is an optional feature that requires additional ports.
# - name: Add DHCP to Firewalld
#   ansible.builtin.firewalld:
#     service: dhcp
#     permanent: true
#     state: enabled

# The DHCP server is an optional feature that requires additional ports.
# - name: Add DHCPv6 to Firewalld
#   ansible.builtin.firewalld:
#     service: dhcpv6
#     permanent: true
#     state: enabled

- name: Create ftl zone
  ansible.builtin.firewalld:
    zone: ftl
    permanent: true
    state: present

# You will have to reload firewalld after adding a zone that you wish to perform immediate actions on
- name: reload service firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded

- name: Add lo interface to ftl zone
  ansible.builtin.firewalld:
    zone: ftl
    interface: lo
    permanent: true
    state: enabled

# FTL is Pi-hole API engine and uses port 4711 on the localhost interface.
- name: All lo interface to ftl zone
  ansible.builtin.firewalld:
    port: 4711/tcp
    zone: ftl
    permanent: true
    state: enabled
    immediate: true

- name: Create a Pi-hole container
  containers.podman.podman_container:
    name: pihole
    image: pihole/pihole:latest
    hostname: pi.hole
    privileged: true
    # capabilities:
    #   - NET_ADMIN
    env:
      TZ: America/New York
      ServerIP: 172.16.199.200
      WEBPASSWORD: "{{ lookup('env', 'PIHOLE_PASSWORD') | default('password', true) }}"
      DNSMASQ_LISTENING: local
      DNSSEC: true
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    label:
      io.containers.autoupdate: image
    network: host
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp"
    #   - "80:80/tcp"
    #   - "443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volume:
      - /home/nleiva/etc-pihole/:/etc/pihole/:z
      - /home/nleiva/etc-dnsmasq.d/:/etc/dnsmasq.d/:z
