- name: Install Podman
  package:
    name: podman
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5

- name: "Creating /home/nleiva/etc-pihole"
  file:
    path: /home/nleiva/etc-pihole
    owner: root
    group: root
    state: directory
    recurse: yes

- name: "Creating /home/nleiva/etc-dnsmasq.d"
  file:
    path: /home/nleiva/etc-dnsmasq.d
    owner: root
    group: root
    state: directory
    recurse: yes

- name: Add HTTP to Firewalld to system-default(public)
  firewalld:
    service: http
    permanent: yes
    state: enabled

- name: Add DNS to Firewalld to system-default(public)
  firewalld:
    service: dns
    permanent: yes
    state: enabled

# The DHCP server is an optional feature that requires additional ports.
# - name: Add DHCP to Firewalld
#   firewalld:
#     service: dhcp
#     permanent: yes
#     state: enabled

# The DHCP server is an optional feature that requires additional ports.
# - name: Add DHCPv6 to Firewalld
#   firewalld:
#     service: dhcpv6
#     permanent: yes
#     state: enabled

- name: Create ftl zone
  firewalld:
    zone: ftl
    permanent: yes
    state: present

# You will have to reload firewalld after adding a zone that you wish to perform immediate actions on
- name: reload service firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: Add lo interface to ftl zone
  firewalld:
    zone: ftl
    interface: lo
    permanent: yes
    state: enabled

# FTL is Pi-hole API engine and uses port 4711 on the localhost interface.
- name: All lo interface to ftl zone
  firewalld:
    port: 4711/tcp
    zone: ftl
    permanent: yes
    state: enabled
    immediate: yes

# - name: "Deploying Pi-hole"
#   raw: podman create -d --name pihole --label "io.containers.autoupdate=image" --network host -e TZ="America/New York" --privileged -v "/home/nleiva/etc-pihole/:/etc/pihole/:z" -v "/home/nleiva/etc-dnsmasq.d/:/etc/dnsmasq.d/:z" --dns=127.0.0.1 --dns=1.1.1.1 --hostname pi.hole -e ServerIP="172.16.199.200" -e WEBPASSWORD=password -e DNSMASQ_LISTENING=local -e DNSSEC=true -e DNS1=1.1.1.1 -e DNS2=1.0.0.1 pihole/pihole:latest

- name: Create a Pi-hole container
  containers.podman.podman_container:
    name: pihole
    image: pihole/pihole:latest
    hostname: pi.hole
    privileged: yes
    # capabilities:
    #   - NET_ADMIN
    env:
      TZ: America/New York
      ServerIP: 172.16.199.200
      WEBPASSWORD: "{{ lookup('env', 'PIHOLE_PASSWORD') | default('password', true) }}"
      DNSMASQ_LISTENING: local
      DNSSEC: true
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    label:
      io.containers.autoupdate: image
    network: host
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp"
    #   - "80:80/tcp"
    #   - "443:443/tcp"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volume:
      - /home/nleiva/etc-pihole/:/etc/pihole/:z
      - /home/nleiva/etc-dnsmasq.d/:/etc/dnsmasq.d/:z