# https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html#adding-custom-facts
- name: Create directory for ansible custom facts
  ansible.builtin.file:
    state: directory
    recurse: true
    path: /etc/ansible/facts.d
    mode: 0755

- name: Ensure ansible custom facts file exists
  ansible.builtin.copy:
    content: "[main]"
    dest: /etc/ansible/facts.d/app.fact
    force: false
    mode: 0644

- name: Add cockpit to custom installed apps
  ansible.builtin.lineinfile:
    path: /etc/ansible/facts.d/app.fact
    regexp: '^cockpit='
    line: 'cockpit=true'
    state: present
    mode: '0644'
    # create: true

- name: Re-read facts after adding custom fact
  ansible.builtin.setup:
    filter: ansible_local

# To check an app ->
# - name: Print DNS
#   ansible.builtin.debug:
#     msg: "DNS was found"
#   when: ansible_local['app']['main']['dns'] is defined
