# ansible-playbook grafana-cloud.yml --ask-vault-pass

- name: Run Grafana Cloud agent
  hosts: rhel
  gather_facts: true

  tasks:
    - name: Include secret vars
      ansible.builtin.include_vars: secret/vars-enc.yml

    - name: Install agent
      ansible.builtin.include_role:
        name: grafana_agent
      vars:
        ansible_become: true

    - name: Finishing debug message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"
