# ansible-playbook grafana-cloud.yml --ask-become-pass --ask-vault-pass

- name: Run Grafana Cloud agent
  hosts: host1*
  gather_facts: yes

  tasks:
    - name: Include secret vars
      include_vars: secret/vars-enc.yml

    - name: Install agent
      include_role:
        name: grafana_agent
      vars:
        ansible_become: yes

    - name: Finishing debug message
      debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"