# ansible-playbook initial-setup.yml --ask-become-pass --ask-vault-pass

- name: Setup my user account
  hosts: rhel-7*
  gather_facts: true
  vars_files:
    - secret/vars-enc.yml
  vars:
    ansible_user: root
    ansible_password: "{{ my_password }}"
    my_user: nleiva

  tasks:
    - name: Initial setup
      ansible.builtin.include_role:
        name: initial_setup
      vars:
        ansible_become: true

    - name: Finishing debug message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"
