# ansible-playbook install-satellite.yml --ask-become-pass --ask-vault-pass

- name: Install Satellite
  hosts: rhel-7
  gather_facts: true
  vars:
    first_time: true

  tasks:
    - name: Include secret vars
      include_vars: secret/vars-enc.yml

    - name: Run Satellite Role
      ansible.builtin.include_role:
        name: satellite
      vars:
        ansible_become: true

    - name: Finishing debug message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"
