# ansible-playbook openscap.yml --ask-become-pass -v

- name: Run OpenSCAP
  hosts: host1*
  gather_facts: true

  tasks:
    - name: Run OpenSCAP role
      ansible.builtin.include_role:
        name: run_openscap
      vars:
        ssg_schema: "/usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml"
        file_path: "/var/www/html/openscap/"
        ansible_become: true
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "8"

    - name: Finishing debug message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"
