# ansible-playbook pi-hole.yml --ask-become-pass -v

- name: Install Pi-hole
  hosts: pi3*
  gather_facts: yes

  pre_tasks:
    - name: Starting debug message
      debug:
        msg: "It will start working on {{ inventory_hostname }}:{{ ansible_host }}"

  roles:
    - role: pi_hole
      become: yes
      vars:
        mode: hw
        domain: lab.home
    - role: firewall_rules
      become: yes

  tasks:
    - name: Finishing debug message
      debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"