# ansible-playbook pi-hole.yml --ask-become-pass -v
# Update whilelist rules:  ansible-playbook pi-hole.yml --ask-become-pass -v --tags whitelist

- name: Install Pi-hole
  hosts: pi5*
  gather_facts: yes

  tasks:
    - name: Run Pi-hole installer
      include_role:
        name: pi_hole
      vars:
        mode: hw
        domain: lab.home
        ansible_become: yes
      tags: always

    - name: Update Firewall rules
      include_role:
        name: firewall_rules
      vars:
        ansible_become: yes

    - name: Finishing debug message
      debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"