# ansible-playbook setup.yml --ask-become-pass -v

- name: Setup Lab machines
  hosts: lab
  gather_facts: yes

  pre_tasks:
    - name: Starting debug message
      debug:
        msg: "It will start working on {{ inventory_hostname }}:{{ ansible_host}}"

  roles:
    - update_pkgs
    - install_pkgs
    - dot_files

  tasks:
    - name: Finishing debug message
      debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host}} is ready"