# ansible-playbook setup.yml -v

- name: Setup Lab machines
  hosts: pi4*
  gather_facts: true

  pre_tasks:
    - name: Starting debug message
      ansible.builtin.debug:
        msg: "It will start working on {{ inventory_hostname }}:{{ ansible_host }}"

  roles:
    - name: update_pkgs
      become: true
    - role: repo-epel
      become: true
      when:
        - ansible_facts['distribution'] in ['CentOS', 'RedHat']
        - not (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")
    - role: repo_backports
      become: true
      when: ansible_facts['distribution'] in ['Debian']
    - role: install_pkgs
      become: true
    - role: basic_settings
      become: true
    - role: custom_facts
      become: true
    - role: dot_files
    - role: firewall_rules
      become: true

    - name: test_internet

  tasks:
    - name: Finishing debug message
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"
