# ansible-playbook setup.yml --ask-become-pass -v

- name: Setup Lab machines
  hosts: host
  gather_facts: yes

  pre_tasks:
    - name: Starting debug message
      debug:
        msg: "It will start working on {{ inventory_hostname }}:{{ ansible_host }}"

  roles:
    - role: update_pkgs
      become: yes
    - role: repo-epel
      become: yes
      when:
        - ansible_facts['distribution'] in ['CentOS', 'RedHat']
        - not (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")
    - role: repo_backports
      become: yes
      when: ansible_facts['distribution'] in ['Debian']
    - role: install_pkgs
      become: yes
    - role: basic_settings
      become: yes
    - role: custom_facts
      become: yes
    - role: dot_files
    - role: firewall_rules
      become: yes
    - role: test_internet

  tasks:
    - name: Finishing debug message
      debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"