# ansible-playbook setup.yml --ask-become-pass -v

- name: Setup Lab machines
  hosts: lab
  gather_facts: yes

  pre_tasks:
    - name: Starting debug message
      debug:
        msg: "It will start working on {{ inventory_hostname }}:{{ ansible_host }}"

  roles:
    - role: update_pkgs
      become: yes
    - role: repo-epel
      become: yes
      when: ansible_facts['distribution'] in ['CentOS', 'RedHat']
    - role: install_pkgs
      become: yes
    - role: dot_files
    - role: test_internet

  tasks:
    - name: Finishing debug message
      debug:
        msg: "{{ inventory_hostname }}:{{ ansible_host }} running {{ ansible_distribution }} {{ ansible_distribution_version }} is ready"