---
# tasks file for linux-install-satellite

- name: Register as user {{ subscription_manager_username }} and subscribe to Satellite Infrastructure Pool with ID {{ satellite_pool_id }}
  redhat_subscription:
    state: present
    username: "{{ subscription_manager_username }}"
    password: "{{ subscription_manager_password }}"
    pool_ids: "{{ satellite_pool_id }}"

- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled
  when: first_time

- name: Enable Satellite repos
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  loop: "{{ satellite_repos }}"

- name: Create directory for ansible custom facts
  file:
    state: directory
    recurse: yes
    path: /etc/ansible/facts.d
    mode: 0755

- name: Ensure ansible custom facts file exists
  copy:
    content: "[main]"
    dest: /etc/ansible/facts.d/app.fact
    force: no
    mode: 0644

- name: Add Satellite to custom installed apps
  lineinfile:
    path: /etc/ansible/facts.d/app.fact
    regexp: '^satellite='
    line: 'satellite=true'
    state: present
    mode: '0644'

- name: Re-read facts after adding custom fact
  setup:
    filter: ansible_local

- name: Install Satellite
  yum:
    name: satellite
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5

- name: Update satellite-installer command
  set_fact:
    satellite_deployment_installer_cmd: "{{ satellite_deployment_installer_cmd
      }} --{{ item.key }}='{{ item.value }}'"
  with_dict: "{{ satellite_deployment_answers }}"

- name: Satellite installation
  command: "{{ satellite_deployment_installer_cmd }}"
  register: command_output
  changed_when: 'command_output.rc == 0'
  async: 3600
  poll: 15