- name: Test reachability to {{ ip_list }}
  ansible.builtin.uri:
    url: "{{ ip_list }}"
    follow_redirects: none
    method: GET
  register: result
  until: result.status == 200
  retries: 4
  delay: 5

- name: Display reachability info
  ansible.builtin.debug:
    msg:
      - "Public IP address: {{ result.json.ip }}"
      - "From {{ result.json.asn.name | default('N/A') }} (ASN {{ result.json.asn.code | default('N/A') }}) in {{ result.json.countrycode }}"
