- name: Install base packages
  package:
    name: "{{ base_software[ansible_distribution_file_variety] }}"
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5