# https://github.com/saltstack/salt/issues/55110#issuecomment-546735717
- name: Fix iptables on Debian Buster
  apt:
    name: iptables
    state: latest
    default_release: buster-backports
  when: ansible_distribution_release == "buster"

- name: Install base packages
  package:
    name: "{{ base_software[ansible_distribution_file_variety] | union(common_software) }}"
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5