---
# Common to all distros
common_software:
  - git
  - wget
  - tree
  - firewalld

# ansible_distribution_file_variety
base_software:
  Debian:
    - dnsutils
    - vim-gui-common
    - vim-runtime
  RedHat:
    - bind-utils
