- name: Clone a dot files repo
  git:
    repo: "{{ dot_repo }}"
    dest: "{{ dot_files_dst }}"
    force: yes

# https://github.com/nleiva/dotfiles#install
- name: Install dot files
  command: "{{ dot_files_dst }}/install.sh"