# RHEL 7 bug? https://bugzilla.redhat.com/show_bug.cgi?id=1501193#c14
- name: Restore restore the SELinux security context of /etc/machine-info
  ansible.builtin.command: restorecon /etc/machine-info
  when:
   - ansible_distribution == "RedHat"
   - ansible_distribution_major_version == "7"

- name: Set the hostname
  ansible.builtin.include_tasks: hostname.yml
