# Ansible Lint for GitHub Action: https://github.com/marketplace/actions/ansible-lint
name: Ansible Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        targets: "*.yml"
        # Avoid annoying
        #  - 'Commands should not change things if nothing needs doing' [301]
        #  - 'Git checkouts must contain explicit version' [401]
        #  - 'Package installs should not use latest' [403]
        args: "-x 301,401,403"